(() => {
'use strict';
const WS='wss://eventsub.wss.twitch.tv/ws?keepalive_timeout_seconds=30';
const API='https://api.twitch.tv/helix';
const OAUTH='https://id.twitch.tv/oauth2/authorize';
const SCOPE='user:read:chat';
const CLIENT='75se22u3rxqy926g81rdxzq6wb4fvt';
const GITHUB_REDIRECT='https://donson85001.github.io/zoebot/index.html';
const GAS='https://script.google.com/macros/s/AKfycbzLet29KonFvVjhxrzf7oM-g-FyfhVkyzYjbRLQtrHeX7zh4KLNXsIbfRdqGnYZuWzzZg/exec';
const $=s=>document.querySelector(s);
const e={clientId:$('#clientId'),redirectUri:$('#redirectUri'),loginBtn:$('#loginBtn'),logoutBtn:$('#logoutBtn'),saveSettingsBtn:$('#saveSettingsBtn'),authInfo:$('#authInfo'),channelLogin:$('#channelLogin'),startBtn:$('#startBtn'),stopBtn:$('#stopBtn'),channelInfo:$('#channelInfo'),badge:$('#connectionBadge'),eventList:$('#eventList'),debug:$('#debugLog'),clearBtn:$('#clearBtn'),showChat:$('#showChat'),chatCount:$('#chatCount'),subCount:$('#subCount'),resubCount:$('#resubCount'),giftCount:$('#giftCount'),lastSubJson:$('#lastSubJson'),copyJsonBtn:$('#copyJsonBtn'),months:$('#publicMonths'),gifts:$('#publicGifts'),apiUrl:$('#publicApiUrl'),key:$('#publicWriteKey'),manualMonths:$('#manualMonths'),manualGifts:$('#manualGifts'),savePublicBtn:$('#savePublicBtn'),loadPublicBtn:$('#loadPublicBtn'),setPublicBtn:$('#setPublicBtn'),publicInfo:$('#publicInfo'),publicStatsUrl:$('#publicStatsUrl')};
const st={token:null,viewer:null,target:null,socket:null,stopped:false,seen:new Set(),counts:{chat:0,sub:0,resub:0,gift:0},last:null,public:{subscriptionMonths:1546,giftSubCount:395}};
const redirect=()=>location.hostname.endsWith('github.io')?GITHUB_REDIRECT:location.href.split('#')[0].split('?')[0];
function log(x){if(e.debug)e.debug.textContent=`[${new Date().toLocaleTimeString('zh-TW',{hour12:false})}] ${x}\n${e.debug.textContent}`.slice(0,30000)}
function status(el,text,mode='muted'){el.textContent=text;el.className=`plain-status ${mode}`}
function badge(text,mode){e.badge.textContent=text;e.badge.className=`badge ${mode}`}
function load(){e.clientId.value=CLIENT;e.redirectUri.value=redirect();e.channelLogin.value=localStorage.getItem('lastChannelLogin')||'';e.apiUrl.value=GAS;e.key.value=localStorage.getItem('publicWriteKey')||'';refreshUrl()}
function save(){localStorage.setItem('twitchClientId',CLIENT);localStorage.setItem('twitchRedirectUri',redirect());localStorage.setItem('lastChannelLogin',e.channelLogin.value.trim());localStorage.setItem('publicApiUrl',GAS);localStorage.setItem('publicWriteKey',e.key.value.trim())}
function nonce(){const a=new Uint8Array(24);crypto.getRandomValues(a);return [...a].map(x=>x.toString(16).padStart(2,'0')).join('')}
function login(){save();const n=nonce();localStorage.setItem('oauthState',n);const u=new URL(OAUTH);u.searchParams.set('response_type','token');u.searchParams.set('client_id',CLIENT);u.searchParams.set('redirect_uri',redirect());u.searchParams.set('scope',SCOPE);u.searchParams.set('state',n);location.assign(u)}
function oauth(){if(!location.hash)return false;const p=new URLSearchParams(location.hash.slice(1));const t=p.get('access_token');if(!t)return false;const expected=localStorage.getItem('oauthState'),got=p.get('state');if(expected&&expected!==got){status(e.authInfo,'OAuth 驗證失敗，請重新登入','error');return false}localStorage.removeItem('oauthState');st.token=t;sessionStorage.setItem('twitchAccessToken',t);history.replaceState(null,'',location.pathname+location.search);return true}
async function helix(path,opt={}){if(!st.token)throw Error('尚未登入 Twitch');const r=await fetch(API+path,{...opt,headers:{Authorization:`Bearer ${st.token}`,'Client-Id':CLIENT,...(opt.body?{'Content-Type':'application/json'}:{})}});const text=await r.text();let d;try{d=JSON.parse(text)}catch{d=text}if(!r.ok)throw Error(`${r.status}: ${d?.message||text}`);return d}
async function validate(){if(!st.token)return false;try{const r=await fetch('https://id.twitch.tv/oauth2/validate',{headers:{Authorization:`OAuth ${st.token}`}});if(!r.ok)throw Error(`Token 驗證失敗 (${r.status})`);const v=await r.json();if(!(v.scopes||[]).includes(SCOPE))throw Error(`缺少 ${SCOPE}`);const u=await helix('/users');st.viewer=u.data?.[0];if(!st.viewer)throw Error('無法取得 Twitch 使用者');status(e.authInfo,`已登入：${st.viewer.display_name} (@${st.viewer.login})`,'ok');return true}catch(err){sessionStorage.removeItem('twitchAccessToken');st.token=null;status(e.authInfo,`登入無效：${err.message}`,'error');return false}}
async function resolve(login){const n=login.trim().replace(/^https?:\/\/(www\.)?twitch\.tv\//i,'').split(/[/?#]/)[0].toLowerCase();if(!n)throw Error('請輸入 Twitch 頻道名稱');const d=await helix(`/users?login=${encodeURIComponent(n)}`);if(!d.data?.[0])throw Error(`找不到頻道：${n}`);return d.data[0]}
async function start(){try{if(!st.viewer&&!(await validate()))throw Error('請先登入 Twitch');st.target=await resolve(e.channelLogin.value);localStorage.setItem('lastChannelLogin',st.target.login);status(e.channelInfo,`目標：${st.target.display_name} (@${st.target.login})`,'ok');st.stopped=false;connect(WS)}catch(err){status(e.channelInfo,err.message,'error');log(err.message)}}
function connect(url){badge('連線中','connecting');if(st.socket)try{st.socket.close()}catch{};const ws=new WebSocket(url);st.socket=ws;ws.onmessage=ev=>message(ws,ev);ws.onerror=()=>log('WebSocket 發生錯誤');ws.onclose=()=>{if(!st.stopped){badge('已斷線','offline');e.startBtn.disabled=false;e.stopBtn.disabled=true}}}
async function message(ws,ev){let p;try{p=JSON.parse(ev.data)}catch{return}const m=p.metadata||{},id=m.message_id;if(id){if(st.seen.has(id))return;st.seen.add(id);if(st.seen.size>2000)st.seen.delete(st.seen.values().next().value)}if(m.message_type==='session_welcome'){try{await subscribe(p.payload.session.id);badge('監聽中','online');e.startBtn.disabled=true;e.stopBtn.disabled=false}catch(err){badge('建立訂閱失敗','offline');status(e.channelInfo,`建立 EventSub 失敗：${err.message}`,'error');log(err.message);try{ws.close()}catch{}}}else if(m.message_type==='session_reconnect'){const u=p.payload.session.reconnect_url;if(u)connect(u)}else if(m.message_type==='notification')notification(p)}
async function subscribe(session){const condition={broadcaster_user_id:st.target.id,user_id:st.viewer.id};for(const type of ['channel.chat.message','channel.chat.notification']){await helix('/eventsub/subscriptions',{method:'POST',body:JSON.stringify({type,version:'1',condition,transport:{method:'websocket',session_id:session}})});log(`EventSub 已建立：${type}`)}}
function tier(x){return x==='1000'?1:x==='2000'?2:x==='3000'?3:x||null}
function card(cat,title,who,msg,params=[]){e.eventList.querySelector('.empty-state')?.remove();const a=document.createElement('article');a.className=`event-item ${cat}`;const meta=document.createElement('div');meta.className='event-meta';meta.textContent=`${new Date().toLocaleTimeString('zh-TW',{hour12:false})}  #${st.target?.login||''}`;const t=document.createElement('div');t.className='event-title';t.textContent=`${title} · ${who}`;const x=document.createElement('div');x.className='event-message';x.textContent=msg||'';a.append(meta,t,x);if(params.length){const w=document.createElement('div');w.className='event-params';params.forEach(v=>{const s=document.createElement('span');s.className='param';s.textContent=v;w.append(s)});a.append(w)}e.eventList.prepend(a);while(e.eventList.children.length>300)e.eventList.lastElementChild.remove()}
function notification(p){const type=p.payload.subscription?.type,ev=p.payload.event||{};if(type==='channel.chat.message'){st.counts.chat++;counts();if(e.showChat.checked)card('chat','聊天室',ev.chatter_user_name||ev.chatter_user_login||'未知',ev.message?.text||'');return}const n=ev.notice_type,who=ev.chatter_is_anonymous?'匿名':(ev.chatter_user_name||ev.chatter_user_login||'未知');if(n==='sub'){const d=ev.sub||{};st.counts.sub++;counts();const item={type:'sub',tier:tier(d.sub_tier),isPrime:!!d.is_prime};last(item);card('sub','新訂閱',who,ev.message?.text||'',Object.entries(item).map(([k,v])=>`${k}=${v}`))}else if(n==='resub'){const d=ev.resub||{},months=Number(d.cumulative_months);st.counts.resub++;counts();const item={type:'resub',tier:tier(d.sub_tier),cumulativeMonths:d.cumulative_months??null,durationMonths:d.duration_months??null,streakMonths:d.streak_months??null};last(item);card('resub','續訂',who,ev.message?.text||'',Object.entries(item).map(([k,v])=>`${k}=${v}`));if(Number.isFinite(months)&&months>0)increment(months,0,p.metadata?.message_id)}else if(n==='community_sub_gift'){const d=ev.community_sub_gift||{},total=Number(d.total),plus=Number.isFinite(total)?Math.floor(total/5):0;st.counts.gift++;counts();const item={type:'community_sub_gift',tier:tier(d.sub_tier),total:d.total??null,cumulativeTotal:d.cumulative_total??null};last(item);card('gift','批次贈訂',who,ev.message?.text||'',Object.entries(item).map(([k,v])=>`${k}=${v}`));if(plus>0)increment(0,plus,p.metadata?.message_id)}else if(n==='sub_gift'){st.counts.gift++;counts();const d=ev.sub_gift||{};const item={type:'sub_gift',tier:tier(d.sub_tier),durationMonths:d.duration_months??null};last(item);card('gift','單筆贈訂',who,ev.message?.text||'',Object.entries(item).map(([k,v])=>`${k}=${v}`))}}
function last(item){st.last=item;e.lastSubJson.textContent=JSON.stringify(item,null,2)}
function counts(){e.chatCount.textContent=st.counts.chat;e.subCount.textContent=st.counts.sub;e.resubCount.textContent=st.counts.resub;e.giftCount.textContent=st.counts.gift}
function stop(){st.stopped=true;try{st.socket?.close(1000,'User stopped')}catch{}st.socket=null;badge('未監聽','offline');e.startBtn.disabled=false;e.stopBtn.disabled=true}
function refresh(){e.months.textContent=st.public.subscriptionMonths;e.gifts.textContent=st.public.giftSubCount;e.manualMonths.value=st.public.subscriptionMonths;e.manualGifts.value=st.public.giftSubCount}
function refreshUrl(){e.publicStatsUrl.textContent=`${GAS}?action=stats`}
async function getStats(){try{const r=await fetch(`${GAS}?action=stats&_=${Date.now()}`,{cache:'no-store'}),d=await r.json();const m=Number(d.subscriptionMonths),g=Number(d.giftSubCount);if(!Number.isFinite(m)||!Number.isFinite(g))throw Error('回傳格式不正確');st.public.subscriptionMonths=m;st.public.giftSubCount=g;refresh();e.publicInfo.textContent=`已讀取：月份 ${m} / 贈禮 ${g}`;e.publicInfo.className='settings-status ok'}catch(err){e.publicInfo.textContent=`讀取失敗：${err.message}`;e.publicInfo.className='settings-status error'}}
async function post(action,payload){const key=e.key.value.trim();if(!key)throw Error('缺少更新金鑰');const r=await fetch(GAS,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({...payload,action,key}),cache:'no-store'});const d=await r.json();if(!r.ok||d.ok===false)throw Error(d.error||d.message||`HTTP ${r.status}`);return d}
async function increment(md,gd,eventId){st.public.subscriptionMonths+=md;st.public.giftSubCount+=gd;refresh();try{const d=await post('increment',{subscriptionMonthsDelta:md,giftSubCountDelta:gd,eventId:eventId||null});st.public.subscriptionMonths=Number(d.subscriptionMonths);st.public.giftSubCount=Number(d.giftSubCount);refresh()}catch(err){log(`試算表同步失敗：${err.message}`)}}
async function setStats(){try{const m=Math.max(0,Math.floor(Number(e.manualMonths.value))),g=Math.max(0,Math.floor(Number(e.manualGifts.value)));const d=await post('set',{subscriptionMonths:m,giftSubCount:g});st.public.subscriptionMonths=Number(d.subscriptionMonths);st.public.giftSubCount=Number(d.giftSubCount);refresh();e.publicInfo.textContent='同步成功';e.publicInfo.className='settings-status ok'}catch(err){e.publicInfo.textContent=`同步失敗：${err.message}`;e.publicInfo.className='settings-status error'}}
e.loginBtn.onclick=login;e.logoutBtn.onclick=()=>{stop();sessionStorage.removeItem('twitchAccessToken');st.token=null;st.viewer=null;status(e.authInfo,'已清除 Twitch 登入','muted')};e.startBtn.onclick=start;e.stopBtn.onclick=stop;e.clearBtn.onclick=()=>{e.eventList.innerHTML='<div class="empty-state">等待事件...</div>';st.counts={chat:0,sub:0,resub:0,gift:0};counts()};e.saveSettingsBtn.onclick=save;e.savePublicBtn.onclick=()=>{save();e.publicInfo.textContent='設定已儲存';e.publicInfo.className='settings-status ok'};e.loadPublicBtn.onclick=getStats;e.setPublicBtn.onclick=setStats;e.copyJsonBtn.onclick=async()=>{if(st.last)await navigator.clipboard.writeText(JSON.stringify(st.last,null,2))};
const modal=$('#settingsModal'),open=$('#settingsBtn'),close=$('#closeSettingsBtn');open.onclick=()=>modal.hidden=false;close.onclick=()=>modal.hidden=true;modal.onclick=x=>{if(x.target===modal)modal.hidden=true};
(async()=>{load();st.token=sessionStorage.getItem('twitchAccessToken');if(location.hash.includes('access_token='))oauth();if(st.token)await validate();await getStats();log('GitHub Pages 版已載入')})();
})();